# Generated by Django 4.2.11 on 2024-05-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('idea', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
            ],
        ),
    ]
