# Generated by Django 4.2.11 on 2024-05-13 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='isGoodIdea',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='month',
            name='position',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
