# Generated by Django 4.2.11 on 2024-05-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_month_isgoodidea_alter_month_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
