# Generated by Django 4.2.11 on 2024-05-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_month_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
