# Generated by Django 4.2.11 on 2024-05-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_month_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
